/*
 * WeatherAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using WeatherAPI.Standard;
using WeatherAPI.Standard.Utilities;


namespace WeatherAPI.Standard.Models
{
    public class TimezoneJsonResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string name;
        private string region;
        private string country;
        private double? lat;
        private double? lon;
        private string tzId;
        private int? localtimeEpoch;
        private string localtime;

        /// <summary>
        /// Local area name.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Local area region.
        /// </summary>
        [JsonProperty("region")]
        public string Region 
        { 
            get 
            {
                return this.region; 
            } 
            set 
            {
                this.region = value;
                OnPropertyChanged("Region");
            }
        }

        /// <summary>
        /// Country
        /// </summary>
        [JsonProperty("country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                OnPropertyChanged("Country");
            }
        }

        /// <summary>
        /// Area latitude
        /// </summary>
        [JsonProperty("lat")]
        public double? Lat 
        { 
            get 
            {
                return this.lat; 
            } 
            set 
            {
                this.lat = value;
                OnPropertyChanged("Lat");
            }
        }

        /// <summary>
        /// Area longitude
        /// </summary>
        [JsonProperty("lon")]
        public double? Lon 
        { 
            get 
            {
                return this.lon; 
            } 
            set 
            {
                this.lon = value;
                OnPropertyChanged("Lon");
            }
        }

        /// <summary>
        /// Time zone
        /// </summary>
        [JsonProperty("tz_id")]
        public string TzId 
        { 
            get 
            {
                return this.tzId; 
            } 
            set 
            {
                this.tzId = value;
                OnPropertyChanged("TzId");
            }
        }

        /// <summary>
        /// Local date and time in unix time
        /// </summary>
        [JsonProperty("localtime_epoch")]
        public int? LocaltimeEpoch 
        { 
            get 
            {
                return this.localtimeEpoch; 
            } 
            set 
            {
                this.localtimeEpoch = value;
                OnPropertyChanged("LocaltimeEpoch");
            }
        }

        /// <summary>
        /// Local date and time
        /// </summary>
        [JsonProperty("localtime")]
        public string Localtime 
        { 
            get 
            {
                return this.localtime; 
            } 
            set 
            {
                this.localtime = value;
                OnPropertyChanged("Localtime");
            }
        }
    }
} 